name: Update dictionaries

on:
  schedule:
    # At 00:00 on Sunday
    - cron:  '0 0 * * 0'

jobs:
  dicthtml:
    runs-on: ubuntu-latest

    # List of locales to generate
    # Note: as of now there is only one locale so it is OK,
    #       but there will be issues when using 2 or more 
    #       because there will be history difference.
    #       A possible fix would be to do a "git pull" before
    #       adding and pusing changes but this is currently
    #       not implemented.
    strategy:
      matrix:
        locale:
          - fr

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Install requirements
      run: python -m pip install -r requirements.txt

    # That step is meant to fail if there is no changes
    - name: Fetch and update the dictionary
      run: python -m scripts
      env:
        WIKI_LOCALE: ${{ matrix.locale }}

    - name: Upload the dictionary
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.TOKEN }}
        file: data/fr/dicthtml-${{ matrix.locale }}.zip
        asset_name: dicthtml-${{ matrix.locale }}.zip
        tag: ${{ matrix.locale }}
        overwrite: true

    - name: Get current count
      id: current_count
      run: echo "::set-output name=count::$(printf "%'d" "$(cat data/${{ matrix.locale }}/words.count)")"

    - name: Push to built branch
      uses: Automattic/action-commit-to-branch@master
      with:
        branch: master
        commit_message: Updated dicthtml-${{ matrix.locale }} (${{ steps.current_count.outputs.count }} words)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
