name: Dependabot Automerge

on:
  pull_request:

jobs:
  worker:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: "Wait for status checks"
        id: wait_for_status_checks
        uses: WyriHaximus/github-action-wait-for-status@v1.8.0
        with:
          checkInterval: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Automerge
        uses: pascalgn/automerge-action@v0.15.6
        if: steps.wait_for_status_checks.outputs.status == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: automerge,!DO_NOT_MERGE
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
