name: Update dictionaries

on:
  schedule:
    # At 00:00 every day
    - cron:  '0 0 * * *'

jobs:
  dicthtml:
    runs-on: ubuntu-latest

    # List of locales to generate
    strategy:
      matrix:
        locale:
          - fr

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install requirements
      run: python -m pip install -r requirements.txt

    - name: Fetch the latest Wiktionary dump
      run: python -Wd -m scripts --fetch-only
      env:
        WIKI_LOCALE: ${{ matrix.locale }}

    - name: Update the dictionary
      run: python -Wd -m scripts --convert-only
      env:
        WIKI_LOCALE: ${{ matrix.locale }}

    - name: Upload the dictionary
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.TOKEN }}
        file: data/${{ matrix.locale }}/dicthtml-${{ matrix.locale }}.zip
        asset_name: dicthtml-${{ matrix.locale }}.zip
        tag: ${{ matrix.locale }}
        overwrite: true
  
    - name: Update the release description
      run: python -Wd -m scripts --update-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WIKI_LOCALE: ${{ matrix.locale }}

    - name: Archive the dictionary
      uses: actions/upload-artifact@v1
      with:
        name: dicthtml-${{ matrix.locale }}.zip
        path: data/${{ matrix.locale }}/dicthtml-${{ matrix.locale }}.zip

    - name: Compress raw data
      run: gzip --best data/${{ matrix.locale }}/data.json

    - name: Archive raw data
      uses: actions/upload-artifact@v1
      with:
        name: data-${{ matrix.locale }}.json.gz
        path: data/${{ matrix.locale }}/data.json.gz
