name: Code quality

on:
  pull_request:
    paths:
    - '**/*.py'

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements
      run: python -m pip install black flake8 mypy
    - name: Code quality checks
      run: 
      - python -m black --check --diff *.py tests
      - python -m flake8 *.py
      - python -m flake8 --ignore=E501 tests
      - python -m mypy *.py
