name: Unit tests

on:
  pull_request:
    paths:
    - '**/*.py'

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements
      run:
      - python -m pip install -r requirements.txt
      - python -m pip install pytest
    - name: Unit tests
      run: python -m pytest -vv tests/
